name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Log in to Private Registry
      uses: docker/login-action@v3
      with:
        registry: registry.phib.net
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Frontend
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: registry.phib.net/portfolio-website:latest

    - name: Build and push Backend
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: registry.phib.net/portfolio-backend:latest
